### ISSUE TITLE
能否提供python 2.X下的pkl data文件

### ISSUE THREAD

**Issue by uk9921** [lc222/seq2seq_chatbot_new#4]
作者貌似是Windows+python3环境吗？如果想用python2会在loaddata时报错
```
ValueError: unsupported pickle protocol: 4
Loading dataset from ./data/dataset-cornell-length10-filter1-vocabSize40000.pkl
```
可以考虑下一多传一份python2版本的pkl文件吗，毕竟用py2的人还是挺多的～～～

**Comment by lc222** [comment]
这个很简单啊，你用python3读取这个文件然后在保存成python2的格式就行了，就这种问题对于大家而言应该都很简单，所以当时就没有专门转换格式~~
